# This is a modifier on the default survival configs
inherit: survival

# This resource pack is identical to survival except is also includes the flat skull model
resource_pack: "http://rp.elmakers.com/Magic-skulls-RP-1.17.zip"
add_resource_pack: "http://rp.elmakers.com/Magic-skulls-RP-1.17.zip"

# Turn back on skull-based icons
url_icons_enabled: true
