# This may seem confusing, but we want all the changes from *future* versions
# The closer we are to current, the fewer changes are required.
inherit: 1.14
resource_pack: "http://rp.elmakers.com/Magic-RP-8-1.zip"
add_resource_pack: "http://rp.elmakers.com/Magic-all-RP-8-1.zip"
