default:
  item: ender_pearl
  item_disabled: ender_pearl
  force_url: true
  url: http://textures.minecraft.net/texture/5163dafac1d91a8c91db576caac784336791a6e18d8f7f62778fc47bf146b6
  url_disabled: http://textures.minecraft.net/texture/1c28376acb23cd93322c0a5d569b48b7cd631a6d65dd4f226adb9e9dd7e5c
  glyph: "\uE900"
