# .
# This file is merged from the files in the following folder:
# .
# https://github.com/elBukkit/MagicPlugin/tree/master/Magic/src/main/resources/defaults/config
# .
# To edit this configuration with the web editor, use
# /mconfig editor
# .
# This turns on the survival configs by default.
# .
# Use
# /mconfig example set
# to turn them off.
# .
# NOTE: Any changes made with the mconfig configure or example commands
# will override any edits made to this file.
# .

example: survival
