# This disables *all* enchanting, including vanilla
disable_enchanting: false

# This controls what players will see when interacting with an enchantment table
# These spells must exit in your configuration for this to work, and "enchant_block" needs to be set.
# enchant_click: progressmenu
# enchant_sneak_click: spellshop
enchant_click: ""
enchant_sneak_click: ""
enchant_click_requires_wand: true

# This can be used to set up a progression system based on clicking an enchant table with your wand.
# enchant_block: enchantment_table
enchant_block: ""
