#
# These are examples that can be fetched via the `/mconfig fetch` command
#
external_examples:
  betterpotter: "https://github.com/grisstyl/BetterPotter/archive/master.zip"
  superheroes: "https://github.com/elBukkit/Magic-Superheroes/archive/main.zip"
