#
# The default path is a base path common to the others
#

default:
  hidden: true
  # This will broadcast rankups. Set to "" if you don't want this.
  upgrade_broadcast: "&6$name &3has advanced to &b$path&3!"
  # This can be used to run other commands on rankup
  # upgrade_commands:
  #   - lp user @pn parent set $path
  effects:
      # These effects will play when a wand is modified as a result of being
      # enchanted or buying a spell.
      # This doesn't really happen anymore with the default configs, the spellshop
      # is responsible for playing effects on purchase.
      enchant:
      -  class: EffectSingle
         sound: entity_player_levelup
         effectlib:
           class: SphereEffect
           iterations: 5
           period: 2
           particle: enchantment_table
           radius: 3
      upgrade:
      -  class: EffectSingle
         sound: entity_player_levelup
      -  class: EffectRing
         firework_power: 1
         radius: 5
         size: 3

