# This config only changes the RP
resource_pack: hires
add_resource_pack: hires

# Override the all and robes RPs so they load the hires versions
alternate_resource_packs:
  all:
    url: "http://rp.elmakers.com/Magic-hires-all-RP-1.17.zip"
  robes:
    url: "http://rp.elmakers.com/Magic-hires-robes-RP-1.17.zip"
