# This is a modifier on the default survival configs
inherit: survival

resource_pack: robes
add_resource_pack: robes

# Alternate resource packs can be accessed with /getrp <pack>
alternate_resource_packs:
  robes:
    url: "http://rp.elmakers.com/Magic-robes-RP-1.17.zip"
