# Make sure these settings get applied when adding this example
example_override: true

# Set this to true to only fill wands with spells created by the player
# Useful in sandbox configs
fill_wand_creator: true

# Give players a sandbox win on join
welcome_wand: sandbox

# This can be used for a server that is hooked up with a live editor
# The editor will touch this file, and the server will automatically
# reload configurations when the configs have changed.
config_update_interval: 2000

# Don't allow use of the Command action, too much potential for griefing
restricted_spell_actions:
  - CommandAction
