# Use RP for 1.15
resource_pack: "https://s3-us-west-2.amazonaws.com/elmakers/Magic/Magic-RP-1.15.zip"
add_resource_pack: "https://s3-us-west-2.amazonaws.com/elmakers/Magic/Magic-all-RP-1.15.zip"
legacy_icons_enabled: true
