base:
  storage:
    mana: subclass
    mana_max: subclass
    mana_regeneration: subclass
    mana_timestamp: subclass
    spell_levels: class
    spells: class
    brushes: class
    path: subclass
    hotbar_count: subclass

    # Attributes are primarily stored on the mage
    # But attributes can also be set on wands to provide attribute buffs.
    attributes: mage,wand

