# This is a modifier on the default survival configs
inherit: survival

resource_pack: "http://rp.elmakers.com/Magic-slimefun-RP-8-1.16.zip"
add_resource_pack: "http://rp.elmakers.com/Magic-slimefun-RP-8-1.16.zip"
