#
# This is a full customization, replacing wands and spells with guns and
# other combat weapons.
#

# No SP here, for now
sp_enabled: false

# Use a special RP
resource_pack: "http://rp.elmakers.com/Magic-war-RP-8-1.16.zip"

# Use a different RP when combined with other configs
add_resource_pack: "http://rp.elmakers.com/Magic-all-RP-8-1.16.zip"

# Alternate resource packs can be accessed with /getrp <pack>
alternate_resource_packs:
  war:
    url: "http://rp.elmakers.com/Magic-war-RP-8-1.16.zip"
