#
# Base templates
#
# These are used to specify defaults for wands and other magic items.
#
# Their use is optional, but using them is a quick way to make wands work in an intuitive way,
# and also ensures your wands will update properly when the plugin updates.
#
base_bound:
  hidden: true
  bound: true
  keep: true
  invulnerable: true
  immortal: true
  track: true
  undroppable: true
  unstashable: false
  indestructible: true

static_wand:
  hidden: true
  mode: inventory
  drop: cycle_hotbar
  left_click: cast
  right_click: toggle
  swap: cycle_hotbar
  quiet: 1
  effect_bubbles: false
  item_attributes:
    GENERIC_ATTACK_SPEED: 10
  item_attribute_slot: mainhand

base_wand:
    hidden: true
    inherit: base_bound
    mode: inventory
    drop: cycle_hotbar
    left_click: cast
    right_click: toggle
    swap: cycle_hotbar
    quiet: 1
    effect_bubbles: false
    item_attributes:
      GENERIC_ATTACK_SPEED: 10
    item_attribute_slot: mainhand

base_sword:
    hidden: true
    inherit: base_bound
    mode: inventory
    drop: cycle_hotbar
    left_click: none
    right_click: toggle
    swap: cycle_hotbar
    quick_cast: true
    quiet: 1

base_bow:
    hidden: true
    inherit: base_bound
    mode: inventory
    drop: toggle
    left_click: none
    right_click: none
    swap: cycle_hotbar
    quiet: 1
