# Add a custom currency that can be used to manifest blocks if you do not have
# the correct blocks in your inventory
custom_currency:
  materia:
    max: 9999
    default: 0
    icon: skull:http://textures.minecraft.net/texture/b11206551e723c356c23b32383abd19e6d7e9e5988f191e7866ae89ed6cb24

# This allows engineering spells to work with a custom currency instead
# of requiring the blocks to build.
# This only affects spells that use `consume: true`
block_exchange:
  override: true
  enabled: true
  currency: materia

  # This is how much each materia is worth in vault currency
  # This is used to translate worth values assigned to blocks in item.yml into materia
  # values, which is the basis for all of the block exchanges.
  # Make this value larger to make blocks worth (and cost) more materia.
  worth: 1

